# -*- coding: utf-8 -*-
"""UCS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JraYcyGKolJiq4wIsAPhJof3WQ_x6oaW
"""

from operator import itemgetter

'''graph = {'Arad': [['Zerind', 75], ['Timisoara', 118], ['Sibiu', 140]],
         'Zerind': [['Oradea', 71], ['Arad', 75]],
         'Oradea': [['Zerind', 71], ['Sibiu', 151]],
         'Sibiu': [['Rimniciu Vilcea', 80], ['Fagaras', 99], ['Arad', 140], ['Oradea', 151]],
         'Fagaras': [['Sibiu', 99], ['Bucharest', 211]],
         'Rimniciu Vilcea': [['Pitesti', 97], ['Craiova', 146], ['Sibiu', 80]],
         'Timisoara': [['Lugoj', 111], ['Arad', 118]],
         'Lugoj': [['Mehadia', 70], ['Timisoara', 111]],
         'Mehadia': [['Lugoj', 70], ['Dobreta', 75, 242]],
         'Dobreta': [['Mehadia', 75], ['Craiova', 120]],
         'Pitesti': [['Craiova', 138], ['Bucharest', 101]],
         'Craiova': [['Pitesti', 138], ['Dobreta', 120], ['Rimniciu Vilcea', 146]],
         'Bucharest': [['Giurgiu', 90], ['Urziceni', 85], ['Fagaras', 211], ['Pitesti', 101]],
         'Giurgiu': [['Bucharest', 90]],
         'Urziceni': [['Vaslui', 142], ['Hirsova', 98], ['Bucharest', 85]],
         'Vaslui': [['Lasi', 92], ['Urziceni', 142]],
         'Lasi': [['Neamt', 87], ['Vaslui', 92]],
         'Neamt': [['Lasi', 87]],
         'Hirsova': [['Eforie', 86], ['Urziceni', 98]],
         'Eforie': [['Hirsova', 86]], }'''


graph = {'A': [['B', 6], ['C', 9], ['E', 1]],
         'B': [['A', 6], ['D', 3], ['E', 4]],
         'C': [['A', 9], ['F', 2], ['G', 3]],
         'D': [['B', 3], ['E', 5], ['F', 7]],
         'E': [['A', 1], ['B', 4], ['D', 5]],
         'F': [['C', 2], ['D', 7], ['E', 6]],
         'G': [['C', 3]] }


def ucs_path(graph, start, goal):
    opened = [[start[0], start[1], [start[0]]]]  # node, cost, path
    closed = []
    
    while opened:
        node = opened.pop(0)
        print("Current:", node)
        
        if node[0] == goal[0]:
            closed.append(node)
            print("Closed:", closed)
            return node[2]
        
        closed.append(node)
        print("Closed:", closed)
        
        opened_nodes = [n[0] for n in opened]
        closed_nodes = [n[0] for n in closed]
        
        for item in graph[node[0]]:
            if item[0] not in opened_nodes and item[0] not in closed_nodes:
                new_cost = node[1] + item[1]
                new_path = node[2] + [item[0]] 
                opened.append([item[0], new_cost, new_path])
        
        print("Open (before sort):", opened)
        opened.sort(key=itemgetter(1))
        print("Sorted open:", opened)
        print("-" * 60)
    
    return "GOAL Not FOUND"

print("\nFinal Path:", ucs_path(graph, ['C', 0], ['B', 0]))
