import random

# miller_rabin generated by Copilot from the is_prime method in RSA.py
def miller_rabin(n, k):
    """ 
    Miller-Rabin Primality Test 
    Args: 
        n: number to test 
        k: number of rounds (higher = more accurate) 
    Returns: True if probably prime, False if composite 
    """ 
    if n < 2: 
        return False 
    if n == 2 or n == 3: 
        return True 
    if n % 2 == 0: 
        return False 
    # Write n-1 as 2^r × d 
    r, d = 0, n - 1 
    while d % 2 == 0: 
        r += 1 
        d //= 2 
    # Witness loop 
    for _ in range(k): 
        a = random.randrange(2, n - 1) 
        x = pow(a, d, n) 
        if x == 1 or x == n - 1: 
            continue 
        for _ in range(r - 1): 
            x = pow(x, 2, n) 
            if x == n - 1: 
                break 
        else: 
            return False 
    return True

def generate_large_prime(bits=1024): 
    """ 
    Generate cryptographically strong prime 
    """ 
    while True: 
        # Generate random odd number 
        candidate = random.getrandbits(bits) 
        candidate |= (1 << bits - 1) | 1 
        # Check divisibility by small primes first 
        small_primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41] 
        if all(candidate % p != 0 for p in small_primes): 
            # Run Miller-Rabin primality test 
            if miller_rabin(candidate, k=40): 
                return candidate